### ISSUE TITLE
Unable to deploy to firebase

### ISSUE THREAD

**Issue by bhavin-harptec** [jonahsnider/firebase-action#3]
Hi,

I am unable to deploy to firebase.

I am getting this error:

**Error: Failed to get Firebase project `my-project-name`. Please make sure the project exists and your account has permission to access it.**

Here is my yml config:
```
    - name: Deploy to Firebase
      uses: pizzafox/firebase-action@1.0.7
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      with:
        args: deploy
```

If I execute following command with my secret token on my local machine, it works:
```
firebase deploy --token "<my-token>"
```

Thanks.

**Comment by kunal-edkit** [comment]
Can you try again with below config?
```
name: Deploy to Firebase
      uses: pizzafox/firebase-action@1.0.7
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      with:
        args: deploy --only hosting:YOUR_PROJECT_ID --non-interactive
```

**Comment by hegargarcia** [comment]
Tried that but failed with: **Error: No currently active project.**

I got it working by generating the Firebase Token again with this commands:
```sh
firebase login:ci --no-localhost
```
And use the same structure in the README example.

```yaml
 uses: pizzafox/firebase-action@1.0.7
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      with:
        args: deploy --only hosting
```

Hope works for you ;)
