### ISSUE TITLE
Doesn't work with GitHub LFS

### ISSUE THREAD

**Issue by Amzd** [jonahsnider/firebase-action#4]
Can't get it to work with LFS, it will not upload the LFS files.

**Comment by Amzd** [comment]
Okay fixed;

```
    - name: Checkout
      uses: actions/checkout@v1
      with:
        lfs: true
# https://stackoverflow.com/questions/61463578/github-actions-actions-checkoutv2-lfs-true-flag-not-converting-pointers-to-act
    - name: Checkout LFS objects
      run: git lfs checkout

```
